/*
 * @Description: Controller extension for APP_GSD_ContractAcceptance Page
 * @Author: Adrian Recio
 * @Date Created: Feb-25-2016
 * @History:
   =====================================================================
       Adrian Recio  -  25-02-16: Created
   =====================================================================
 */
public without sharing class APP_GSD_ContractAcceptanceExt extends APP_GSD_BaseController{
    /*  Description: Class contructor
     *  Author: Adrian Recio
     *  Date Created: 4-APR-2014
     *  Parameter standard controller
     *  Return: na
     */
    public APP_GSD_ContractAcceptanceExt(ApexPages.StandardController appController){
    }  
}