@IsTest
private with Sharing class consumerAnzCapitalGeComOriginationsTest{

   private static testMethod void coverWsdlClasses(){
   
   Test.startTest();

   new consumerAnzCapitalGeComOriginations.BusinessContext();
   new consumerAnzCapitalGeComOriginations.ServiceContext();
   new consumerAnzCapitalGeComOriginations.ExceptionCollection();
   new consumerAnzCapitalGeComOriginations.ConsumerContext ();
   new consumerAnzCapitalGeComOriginations.Exception_x();
   new consumerAnzCapitalGeComOriginations.POADetail();
   new consumerAnzCapitalGeComOriginations.verifyAMLDataType();
   new consumerAnzCapitalGeComOriginations.amlApplicantsCollection();
   new consumerAnzCapitalGeComOriginations.amlApplicantType();
   new consumerAnzCapitalGeComOriginations.IdDetail();
   new consumerAnzCapitalGeComOriginations.brokerDetailsType();
   new consumerAnzCapitalGeComOriginations.cancelApplicationRequest_element();
   new consumerAnzCapitalGeComOriginations.verifyPOIResponse_element();
   new consumerAnzCapitalGeComOriginations.applicationResponseType();
   new consumerAnzCapitalGeComOriginations.updateApplicationResponse_element();
   new consumerAnzCapitalGeComOriginations.verifyAMLRequest_element();
   new consumerAnzCapitalGeComOriginations.reportDetails();
   new consumerAnzCapitalGeComOriginations.acceptContractRequest_element();
   
   new consumerAnzCapitalGeComOriginations.submitApplicationResponse_element ();
   new consumerAnzCapitalGeComOriginations.updatePartialApplicationResponse_element ();
   new consumerAnzCapitalGeComOriginations.verifyCapacityResponse_element();
   new consumerAnzCapitalGeComOriginations.cancelApplicationResponse_element ();
   new consumerAnzCapitalGeComOriginations.applicationCpuOverrideDataType ();
   new consumerAnzCapitalGeComOriginations.thirdPartyDetailsDataType ();
   new consumerAnzCapitalGeComOriginations.acceptContractResponse_element ();
   new consumerAnzCapitalGeComOriginations.checkHealthDataType();
   new consumerAnzCapitalGeComOriginations.confirmContractReceivedResponse_element ();
   new consumerAnzCapitalGeComOriginations.insuranceCollection ();
   new consumerAnzCapitalGeComOriginations.applicantType ();


   new consumerAnzCapitalGeComOriginations.verifyPOIRequest_element();
   new consumerAnzCapitalGeComOriginations.confirmContractReceivedRequest_element();
   new consumerAnzCapitalGeComOriginations.applicationDataType();
   new consumerAnzCapitalGeComOriginations.serviceFault_element();
   new consumerAnzCapitalGeComOriginations.approveApplicationDataType();
   new consumerAnzCapitalGeComOriginations.approveApplicationResponse_element();
   new consumerAnzCapitalGeComOriginations.approveApplicationRequest_element();
   new consumerAnzCapitalGeComOriginations.checkHealthRequest_element();
   new consumerAnzCapitalGeComOriginations.applicantCollection();


   new consumerAnzCapitalGeComOriginations.declineApplicationRequest_element();
   new consumerAnzCapitalGeComOriginations.checkHealthResponse_element();
   new consumerAnzCapitalGeComOriginations.verifyAMLResponse_element();
   new consumerAnzCapitalGeComOriginations.applicationCustomerDataType();
   new consumerAnzCapitalGeComOriginations.applicationPartialCustomerDataType();
   new consumerAnzCapitalGeComOriginations.applicationCapacityDataType();
   new consumerAnzCapitalGeComOriginations.verifyCapacityRequest_element();
   new consumerAnzCapitalGeComOriginations.submitApplicationRequest_element();
   new consumerAnzCapitalGeComOriginations.applicationSupportingDataType();
   new consumerAnzCapitalGeComOriginations.updateApplicationRequest_element();
   new consumerAnzCapitalGeComOriginations.reportDetail();
   new consumerAnzCapitalGeComOriginations.debtCollection();
   
   
   new consumerAnzCapitalGeComOriginations.declineApplicationResponse_element();
   new consumerAnzCapitalGeComOriginations.assetCollection();
   new consumerAnzCapitalGeComOriginations.disbursementCollection();
   new consumerAnzCapitalGeComOriginations.productDetailsType();
   new consumerAnzCapitalGeComOriginations.fingerPrintDetailsType();
   new consumerAnzCapitalGeComOriginations.disbursementDetailsType();
   new consumerAnzCapitalGeComOriginations.insuranceDetailsType();
   new consumerAnzCapitalGeComOriginations.offerDetailsType();
   new consumerAnzCapitalGeComOriginations.collateralDetailsType();

   
   new consumerAnzCapitalGeComOriginations.collateralCollection();
   new consumerAnzCapitalGeComOriginations.riskReferralDetailsType();
   new consumerAnzCapitalGeComOriginations.riskUserDataType();
   new consumerAnzCapitalGeComOriginations.timeAtAddressType();
   new consumerAnzCapitalGeComOriginations.personalReferenceDataCollection();
   new consumerAnzCapitalGeComOriginations.personalDetailsType();
   new consumerAnzCapitalGeComOriginations.Address();
   new consumerAnzCapitalGeComOriginations.clvDetailsCollection();
   new consumerAnzCapitalGeComOriginations.clvDetailsType();
   
   
   new consumerAnzCapitalGeComOriginations.PersonalReferenceData();
   new consumerAnzCapitalGeComOriginations.budgetDetailsType();
   new consumerAnzCapitalGeComOriginations.assetDetails();
   new consumerAnzCapitalGeComOriginations.debtDetails();
   new consumerAnzCapitalGeComOriginations.expenseDetails();
   new consumerAnzCapitalGeComOriginations.timeWithEmployerType();
   new consumerAnzCapitalGeComOriginations.incomeDetails();
   new consumerAnzCapitalGeComOriginations.employerContactPhoneType();
   new consumerAnzCapitalGeComOriginations.confirmContractReceivedDataType();
   
   new consumerAnzCapitalGeComOriginations.expensesDetailsArray();
   new consumerAnzCapitalGeComOriginations.propertyDetailsArray();
   new consumerAnzCapitalGeComOriginations.expensesDetails();
   new consumerAnzCapitalGeComOriginations.propertyDetails();
   
   
   
   new consumerAnzCapitalGeComOriginations.decisionDataType();
   new consumerAnzCapitalGeComOriginations.refinanceAccountsCollection();
   new consumerAnzCapitalGeComOriginations.CustomerDetail();
   new consumerAnzCapitalGeComOriginations.acceptContractDataType();
   new consumerAnzCapitalGeComOriginations.CustomerDetails();
   new consumerAnzCapitalGeComOriginations.refinanceAccountType();
   new consumerAnzCapitalGeComOriginations.verifyPOIDataType();
   new consumerAnzCapitalGeComOriginations.poiApplicantType();
   new consumerAnzCapitalGeComOriginations.poiApplicantsCollection();
   
   new consumerAnzCapitalGeComOriginations.poiincomeDetails();
   new consumerAnzCapitalGeComOriginations.loanDetailsType();
   new consumerAnzCapitalGeComOriginations.repaymentDetailsArray();
   new consumerAnzCapitalGeComOriginations.feeDetails();
   new consumerAnzCapitalGeComOriginations.repaymentDetails();
   new consumerAnzCapitalGeComOriginations.loanPurposeDetails();
   new consumerAnzCapitalGeComOriginations.branchDetailsType();
   new consumerAnzCapitalGeComOriginations.OriginationApplicationServiceSOAP();

   
   Test.stopTest();

   }
   
   
   
   
  private static testMethod void coverWsdlVariables(){  
   new consumerAnzCapitalGeComOriginations.Exception_x().code='Test';
   new consumerAnzCapitalGeComOriginations.Exception_x().message='Test';
   new consumerAnzCapitalGeComOriginations.Exception_x().detailedMessage='Test';
   new consumerAnzCapitalGeComOriginations.Exception_x().sourceSystem='Test';
   
   new consumerAnzCapitalGeComOriginations.POADetail ().poaType='Test';
   new consumerAnzCapitalGeComOriginations.POADetail ().poaReferenceNo='Test';
   new consumerAnzCapitalGeComOriginations.POADetail ().poaIssuer='Test';
   new consumerAnzCapitalGeComOriginations.POADetail ().poaProvidedFlag=TRUE;
   
   new consumerAnzCapitalGeComOriginations.verifyAMLDataType().sfApplicationId='Test';
   new consumerAnzCapitalGeComOriginations.verifyAMLDataType().applicationId='Test';
   new consumerAnzCapitalGeComOriginations.IdDetail().identificationType='Test';
   new consumerAnzCapitalGeComOriginations.IdDetail ().iDNo='Test';
   
   new consumerAnzCapitalGeComOriginations.IdDetail().issueState='Test';
   new consumerAnzCapitalGeComOriginations.IdDetail().issueCountry='Test';
   new consumerAnzCapitalGeComOriginations.IdDetail().issuer='Test';
   new consumerAnzCapitalGeComOriginations.IdDetail().version='Test';
   
   new consumerAnzCapitalGeComOriginations.brokerDetailsType().sfBrokerId='Test';
   new consumerAnzCapitalGeComOriginations.brokerDetailsType().firstName='Test';
   new consumerAnzCapitalGeComOriginations.brokerDetailsType().lastName='Test';
   new consumerAnzCapitalGeComOriginations.brokerDetailsType().accountName='Test';
   
   new consumerAnzCapitalGeComOriginations.brokerDetailsType().entityName='Test';
   new consumerAnzCapitalGeComOriginations.brokerDetailsType().aggregatorAccountName='Test';
   new consumerAnzCapitalGeComOriginations.brokerDetailsType().suburb='Test';
   new consumerAnzCapitalGeComOriginations.brokerDetailsType().state='Test';
   
   new consumerAnzCapitalGeComOriginations.brokerDetailsType().postCode='Test';
   new consumerAnzCapitalGeComOriginations.brokerDetailsType().landlineNumber='Test';
   new consumerAnzCapitalGeComOriginations.brokerDetailsType().mobileNumber='Test';
   new consumerAnzCapitalGeComOriginations.brokerDetailsType().accreditationStatus='Test';
   
   
   }
    private static testMethod void coverWsdlMethods(){  
    System.Test.setMock(WebServiceMock.class, new WebServiceMockImpl());
       consumerAnzCapitalGeComOriginations metaDataService = new consumerAnzCapitalGeComOriginations();
        // Invoke operations    
        Test.startTest();     
      consumerAnzCapitalGeComOriginations.OriginationApplicationServiceSOAP  OrigAppSoap= new consumerAnzCapitalGeComOriginations.OriginationApplicationServiceSOAP();
      OrigAppSoap.verifyAML(null,null);
      OrigAppSoap.confirmContractReceived(null,null);
      OrigAppSoap.verifyPOI(null,null);
      OrigAppSoap.checkHealth(null,null);
      OrigAppSoap.submitApplication(null,null,null,null);
      OrigAppSoap.updatePartialApplication(null,null);
      OrigAppSoap.declineApplication(null,null,null);
      OrigAppSoap.verifyCapacity(null,null);
      OrigAppSoap.checkHealth(null,null);
      OrigAppSoap.acceptContract(null,null);
      OrigAppSoap.approveApplication(null,null);
      OrigAppSoap.updateApplication(null,null,null,null,null,null,null,null);
      OrigAppSoap.cancelApplication(null,null,null);
      
      
        Test.stopTest();
    
    }
   public class WebServiceMockImpl implements WebServiceMock
    {
        public void doInvoke(
            Object stub, Object request, Map<String, Object> response,
            String endpoint, String soapAction, String requestName,
            String responseNS, String responseName, String responseType)
        {
            if(request instanceof consumerAnzCapitalGeComOriginations.verifyAMLRequest_element)
                response.put('response_x', new consumerAnzCapitalGeComOriginations.verifyAMLResponse_element());
            return;
            if(request instanceof consumerAnzCapitalGeComOriginations.confirmContractReceivedRequest_element)
                response.put('response_x', new consumerAnzCapitalGeComOriginations.confirmContractReceivedResponse_element());
            return;
            if(request instanceof consumerAnzCapitalGeComOriginations.confirmContractReceivedRequest_element)
                response.put('response_x', new consumerAnzCapitalGeComOriginations.confirmContractReceivedResponse_element());
            return;
            if(request instanceof consumerAnzCapitalGeComOriginations.verifyPOIRequest_element)
                response.put('response_x', new consumerAnzCapitalGeComOriginations.verifyPOIResponse_element());
            return;
            
        }
        
    }
          
  
}